from langchain_groq import ChatGroq  
from langchain.prompts import PromptTemplate 
from langchain.schema.output_parser import StrOutputParser 
from langchain.schema.runnable import RunnablePassthrough  
from config import config

# Initialize Groq model with API key
groq_chat = ChatGroq(groq_api_key=config.GROQ_API_KEY, model_name=config.MODEL_NAME)

def format_docs(docs):
    """
    Formats the documents into a single string for context.

    Parameters:
    docs (list): A list of document objects. Each document object should have a 'page_content' attribute.

    Returns:
    str: A string containing the concatenated 'page_content' of all documents, separated by newlines.
    """
    return "\n\n".join(doc.page_content for doc in docs)

def run_chain(prompt_template, inputs):
    """
    Runs the prompt chain with the given prompt template and inputs.

    Parameters:
    prompt_template (PromptTemplate): A prompt template object that defines the structure and content of the prompt.
    inputs (dict): A dictionary containing the inputs for the prompt template, such as context and question.

    Returns:
    str: The output generated by the prompt chain, parsed as a string.
    """
    chain = RunnablePassthrough() | prompt_template | groq_chat | StrOutputParser()
    return chain.invoke(inputs)

# Define prompt templates
def get_prompt_template(use_case):
    if use_case == "generation":
        return PromptTemplate(
            input_variables=["context", "question"],
            template="""
            <s> [INST] You are an expert assistant providing detailed information specifically about Vishwakarma Institute of Technology (VIT), Pune. 
            Please ensure that your response follows these rules:
            Rules:
            1. Only provide information about Vishwakarma Institute of Technology(VIT), Pune.
            2. Always answer in polite and professional manner.
            3. Answer the user query in structured format and make sure the answer is clear, concise and easy to read.

            Guidelines:
            2. Always base your responses on the provided documents. If the documents lack relevant information, politely inform the user that the information is not available and do not specify the internal working of the application.
            3. Identify what the user whats to do and always provide a link in the response based on the query.
            4. When a user provides their MHT-CET percentile, compare it with the cutoff percentiles for MHTCET for various branches and inform them whether they are eligible for admission.
            5. If the user requests steps, guidance for a precedure such as admission then respond in point wise manner.

            Response format:
            Details: [Provide a friendly and helpful response based on the context.]

            [/INST] </s>
            [INST] 
            Question: {question}
            Context: {context}
            Answer: [/INST]
            """
        )
    
    if use_case == "chat_with_pdf":
        return PromptTemplate(
            input_variables=["context", "question", "query"],
            template="""
            <s> [INST] You are an expert assistant specialized in providing detailed and accurate information about Vishwakarma Institute of Technology (VIT), Pune. Users may upload their marks documents containing Merit Rank and CET Percentile Scores. You will assist them with queries related to admissions based on their scores. Please adhere to the following guidelines:

            Guidelines:
            1. Scope: Provide information exclusively related to Vishwakarma Institute of Technology (VIT), Pune, focusing on admissions criteria, cutoff scores, branch allocations, percentiles, ranks, and related queries based on the user's uploaded marks.
            2. Source of Information: Base your responses solely on the provided documents, which include the user's Merit Rank and CET Percentile Scores, as well as VIT's admission details. If the necessary information is not available within the documents, politely inform the user that the information is unavailable without disclosing any internal processes.
            3. Length: Keep your response concise, not exceeding 80 words.
            4. User Intent & Links: Understand the user's intent (e.g., seeking branch allocation based on marks) and include relevant links or resources from the provided documents in your response based on the query.
            5. Data Interpretation: Accurately interpret the user's Merit Rank and Percentile Scores from the uploaded documents to provide precise and relevant information.
            6. Branch Suggestion: Use the Percentile Scores to suggest possible branches the user is eligible for, referencing the latest cutoff percentiles for each branch.
            7. If user doesnt specify the examination for cutoffs, provide the cutoffs for both MHTCET and JEE.

            Response Format:
            Details: [Provide a clear, friendly, and helpful response based on the context.]

            Original User Question: {question}
            Query: {query}
            Context: {context}

            Answer: [/INST]
        """
    )
